# -*- coding: utf-8 -*-
"""Train the Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YfnzlX7mx9Aa5BCFK8PHQq1EWrQpFVd6

# Setup

Clone repo, install dependencies and check PyTorch and GPU.
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images

clear_output()
print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

"""# Google Drive Connection Establishment"""

from google.colab import drive
drive.mount('/content/gdrive')
# this creates a symbolic link so that now the path /content/gdrive/My\ Drive/ is equal to /mydrive
!ln -s /content/gdrive/My\ Drive/ /mydrive

"""#Data Preparation"""

# Commented out IPython magic to ensure Python compatibility.
# %mkdir project_files

!cp -av /mydrive/project/images/ /content/yolov5/project_files
!cp -av /mydrive/project/cfg/ /content/yolov5/project_files
!cp -av /mydrive/project/labels/ /content/yolov5/project_files

"""#Optional for Reporting Results"""

# Commented out IPython magic to ensure Python compatibility.
# Weights & Biases  (optional)
# %pip install -q wandb
import wandb
wandb.login()

"""#Training

**Copy & Paste to Console**

function ClickConnect(){ console.log("Working"); document.querySelector("colab-toolbar-button#connect").click() } setInterval(ClickConnect,60000)
"""

# Train YOLOv5s on Dataset for 3 epochs
!python train.py --data /project_files/cfg/cfg.yaml --weights yolov5s.pt

"""#Output"""

from utils.plots import plot_results 
plot_results(save_dir='runs/train/exp')  # plot all results*.txt as results.png
Image(filename='runs/train/exp/results.png', width=800)